name: fazendados

services:
  fazendados-db:
    container_name: fazendados-db
    image: imresamu/postgis:17-3.5-alpine3.21
    environment:
      POSTGRES_DB: fazendados
      POSTGRES_USER: fazendados
      POSTGRES_PASSWORD: fazendados
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fazendados -d fazendados"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - fazendados_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  fazendados_postgres_data:
    name: fazendados_postgres_data
